name: "Avgjør pakkeversjon og docker tag"
description: "Avgjør pakkeversjon og docker tag basert på GitVersion"
branding:
  icon: 'tag'
  color: 'black'

inputs:
  docker_registry:
    description: 'Docker registry, f.eks. pnweplatformcr.azurecr.io'
    default: 'pnweplatformcr.azurecr.io'
    type: string
  docker_image:
    description: 'Docker image navn, f.eks. storsak/sak/frontend'
    default: ''
    type: string
  override_config:
    description: 'Overstyring av GitVersion konfigurasjonselementer i YAML format'
    default: ''
    type: string

outputs:
  deployTag:
    description: "Deploy tag, docker repository og image navn med tag som skal deployes til miljø"
    value: ${{ steps.avgjoer_versjon_og_tag.outputs.deploy_tag }}
  dockerTags:
    description: "Docker repository og image navn med tags som skal deployes til container registry"
    value: ${{ steps.avgjoer_versjon_og_tag.outputs.docker_tags }}
  version:
    description: "Pakkeversjon som skal brukes ved deploy til pakke registry"
    value: ${{ steps.avgjoer_versjon_og_tag.outputs.version }}
  is_alpha:
    description: "Boolsk verdi som indikerer om versjonen er en alpha/prerelease versjon"
    value: ${{ steps.avgjoer_versjon_og_tag.outputs.is_alpha }}
  gitVersionMajorMinorPatch:
    description: "GitVersion Major.Minor.Patch versjon - kan brukes for å debugge eller håndtere unntakstilfeller"
    value: ${{ steps.version_step.outputs.majorMinorPatch }}
  gitVersionSemVer:
    description: "GitVersion SemVer versjon - kan brukes for å debugge eller håndtere unntakstilfeller"
    value: ${{ steps.version_step.outputs.semVer }}

runs:
  using: "composite"
  steps:
  - name: Hent kode
    uses: actions/checkout@v6
    with:
      fetch-depth: 0

  - name: Installer GitVersion
    uses: gittools/actions/gitversion/setup@v4.2.0
    with:
      versionSpec: '6.4.x'

  - name: Finn neste versjon
    id: version_step
    uses: gittools/actions/gitversion/execute@v4.2.0
    with:
      overrideConfig: ${{ inputs.override_config}}

  - name: Avgjør versjon og tag verdier
    id: avgjoer_versjon_og_tag
    shell: bash
    run: |
      echo "GitVersion MajorMinorPatch: ${{ steps.version_step.outputs.majorMinorPatch }}"
      echo "GitVersion SemVer: ${{ steps.version_step.outputs.semVer }}"

      LATEST_TAG="${{ inputs.docker_registry }}/${{ inputs.docker_image }}:latest"
      GITVERSION_TAG="${{ inputs.docker_registry }}/${{ inputs.docker_image }}:${{ steps.version_step.outputs.majorMinorPatch }}"
      GITVERSION_SEMVER_TAG="${{ inputs.docker_registry }}/${{ inputs.docker_image }}:${{ steps.version_step.outputs.semVer }}"

      if [ -n "${{ github.ref_name }}" ] && [[ "${{ github.ref_name }}" == "main" ]]; then
        if [ -n "${{ inputs.docker_image }}" ]; then
          echo "deploy_tag=$GITVERSION_TAG" >> $GITHUB_OUTPUT
          echo "docker_tags=$LATEST_TAG,$GITVERSION_TAG" >> $GITHUB_OUTPUT
          echo "Bruker tags: $LATEST_TAG,$GITVERSION_TAG"
        fi

        echo "version=${{ steps.version_step.outputs.majorMinorPatch }}" >> $GITHUB_OUTPUT
        echo "Setter version til ${{ steps.version_step.outputs.majorMinorPatch }}"
        echo "is_alpha=false" >> $GITHUB_OUTPUT
        echo "Setter is_alpha til false"
      elif [ -n "${{ github.ref_name }}" ] && [[ "${{ github.ref_name }}" == v* ]]; then
        if [ -n "${{ inputs.docker_image }}" ]; then
          echo "deploy_tag=$GITVERSION_TAG" >> $GITHUB_OUTPUT
          echo "docker_tags=$GITVERSION_TAG" >> $GITHUB_OUTPUT
          echo "Bruker tag: $GITVERSION_TAG"
        fi

        echo "version=${{ steps.version_step.outputs.majorMinorPatch }}" >> $GITHUB_OUTPUT
        echo "Setter version til ${{ steps.version_step.outputs.majorMinorPatch }}"
        echo "is_alpha=false" >> $GITHUB_OUTPUT
        echo "Setter is_alpha til false"
      else
        if [ -n "${{ inputs.docker_image }}" ]; then
          # I en feature/bugfiks branch - bruk neste versjon som tag
          echo "deploy_tag=$GITVERSION_SEMVER_TAG" >> $GITHUB_OUTPUT
          echo "docker_tags=$GITVERSION_SEMVER_TAG" >> $GITHUB_OUTPUT
          echo "Bruker tag med prerelease label: $GITVERSION_SEMVER_TAG"
        fi

        echo "version=${{ steps.version_step.outputs.semVer }}" >> $GITHUB_OUTPUT
        echo "Setter version til ${{ steps.version_step.outputs.semVer }}"
        echo "is_alpha=true" >> $GITHUB_OUTPUT
        echo "Setter is_alpha til true"
      fi
