name: "Avgjør pakkeversjon og container image tag"

on:
  workflow_call:
    inputs:
      container_registry:
        description: 'Container registry, f.eks. egenacr.azurecr.io'
        default: 'egenacr.azurecr.io'
        type: string
      container_image_name:
        description: 'Container image navn, f.eks. mappe/undermappe/frontend'
        default: ''
        type: string
      override_config:
        description: 'Overstyring av GitVersion konfigurasjonselementer i YAML format'
        default: ''
        type: string
    outputs:
      deploy_tag:
        description: "Deploy tag: registry, image navn og tag som skal deployes til miljø"
        value: ${{ jobs.finn-versjon.outputs.deploy_tag }}
      container_image_tags:
        description: "Registry, image navn og tags som skal pushes til container registry"
        value: ${{ jobs.finn-versjon.outputs.container_image_tags }}
      image_tags:
        description: "Kun image tags (uten registry og image navn)"
        value: ${{ jobs.finn-versjon.outputs.image_tags }}
      version:
        description: "Pakkeversjon som skal brukes ved deploy til pakke registry"
        value: ${{ jobs.finn-versjon.outputs.version }}
      is_alpha:
        description: "Boolsk verdi som indikerer om versjonen er en alpha/prerelease versjon"
        value: ${{ jobs.finn-versjon.outputs.is_alpha }}
      git_version_major_minor_patch:
        description: "GitVersion Major.Minor.Patch versjon - kan brukes for å debugge eller håndtere unntakstilfeller"
        value: ${{ jobs.finn-versjon.outputs.git_version_major_minor_patch }}
      git_version_semver:
        description: "GitVersion SemVer versjon - kan brukes for å debugge eller håndtere unntakstilfeller"
        value: ${{ jobs.finn-versjon.outputs.git_version_semver }}

permissions:
  contents: read

jobs:
  finn-versjon:
    runs-on: ubuntu-latest
    outputs:
      deploy_tag: ${{ steps.gitversion.outputs.deploy_tag }}
      container_image_tags: ${{ steps.gitversion.outputs.container_image_tags }}
      image_tags: ${{ steps.gitversion.outputs.image_tags }}
      version: ${{ steps.gitversion.outputs.version }}
      is_alpha: ${{ steps.gitversion.outputs.is_alpha }}
      git_version_major_minor_patch: ${{ steps.gitversion.outputs.git_version_major_minor_patch }}
      git_version_semver: ${{ steps.gitversion.outputs.git_version_semver }}
    steps:
      - name: Avgjør pakkeversjon og container image tag
        id: gitversion
        uses: hwinther/reusable-workflows/.github/actions/gitversion@feat/update-gitversion
        with:
          container_registry: ${{ inputs.container_registry }}
          container_image_name: ${{ inputs.container_image_name }}
          override_config: ${{ inputs.override_config }}
