name: "Validate version references"

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  validate-version-refs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: "24.x"

      - name: Validate internal version references
        run: node ./scripts/validate-version-refs.mjs
